spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.SystemMail.mail: debug

mail:
  contentType: text/html; charset=utf-8
  encoding: base64
  returnPath: jwpark@infomail.co.kr
  mimeVersion: 1.0
  charset: UTF-8
domain:
  domainConnectionInfo:
    naver.com: 10
    nate.com: 10
    daum.net: 6
    default: 15

